### PR TITLE
Shared vault for other admin things

### PR DESCRIPTION
**Pull request by mattrasband**
This adds a new vault file that is just a way to hold shared info for the community admins.

It currently has our email and twitter info.

I also just made it a default via config to look for a `.pass` file - so if anyone is manually calling `--ask-vault-pass` they will see an error like this:

```
Usage: ansible-playbook playbook.yml

ansible-playbook: error: --ask-vault-pass and --vault-password-file are mutually exclusive
```

### CODE REVIEW

**Comment by ovv** [comment]
I'm not really sure we should put that here. Maybe the community repo is more appropriate ?

**Comment by mattrasband** [comment]
I debated that myself, and the only reason I settled on here is to keep all ansible related things together... Hmm...

**Comment by ovv** [comment]
Well we don't use twitter/gmail account info in the ansible at the moment.
We also might want to give server/ansible access to someone without necessarily give him access to the twitter/gmail.

**Comment by mattrasband** [comment]
Fair enough, I'll move it. Though I don't anticipate more than CI or admins
running the ansible playbooks :)

**Comment by mattrasband** [comment]
Closing, I need to move this to another repo and forgot to close this out.

**Pull request closed without merging**
